var data = [
  { identifier: "empty", png: "emerald_placeholder" },
  { identifier: "acacia_boat", png: "boat_acacia" },
  { identifier: "acacia_button", png: "planks_acacia" },
  { identifier: "acacia_door", png: "door_acacia" },
  { identifier: "acacia_fence_gate", png: "planks_acacia" },
  { identifier: "acacia_pressure_plate", png: "planks_acacia" },
  { identifier: "acacia_sign", png: "sign_acacia" },
  { identifier: "acacia_stairs", png: "planks_acacia" },
  { identifier: "acacia_standing_sign", png: "sign_acacia" },
  { identifier: "acacia_trapdoor", png: "acacia_trapdoor" },
  { identifier: "acacia_wall_sign", png: "sign_acacia" },
  { identifier: "activator_rail", png: "rail_detector" },
  { identifier: "agent_spawn_egg", png: "egg_agent" },
  { identifier: "air", png: "stone" },
  { identifier: "allow", png: "build_allow" },
  { identifier: "amethyst_block", png: "amethyst_block" },
  { identifier: "amethyst_cluster", png: "amethyst_cluster" },
  { identifier: "amethyst_shard", png: "amethyst_shard" },
  { identifier: "ancient_debris", png: "ancient_debris_side" },
  { identifier: "andesite_stairs", png: "stone_andesite" },
  { identifier: "anvil", png: "anvil_top_damaged_0" },
  { identifier: "apple", png: "apple" },
  { identifier: "armor_stand", png: "armor_stand" },
  { identifier: "arrow", png: "arrow" },
  { identifier: "axolotl_bucket", png: "bucket_axolotl" },
  { identifier: "axolotl_spawn_egg", png: "bucket_axolotl" },
  { identifier: "azalea", png: "azalea_side" },
  { identifier: "azalea_leaves", png: "azalea_leaves_opaque" },
  { identifier: "azalea_leaves_flowered", png: "azalea_leaves_flowers_opaque" },
  { identifier: "baked_potato", png: "potato_baked" },
  //{ identifier: "balloon", png: "balloon" },
  { identifier: "bamboo", png: "bamboo" },
  { identifier: "bamboo_sapling", png: "bamboo_sapling" },
  { identifier: "banner", png: "wool_colored_white" },
  { identifier: "banner_pattern", png: "banner_pattern" },
  { identifier: "barrel", png: "barrel_side" },
  { identifier: "barrier", png: "barrier" },
  { identifier: "basalt", png: "basalt_top" },
  { identifier: "bat_spawn_egg", png: "egg_bat" },
  { identifier: "beacon", png: "beacon" },
  { identifier: "bed", png: "bed_red" },
  { identifier: "bedrock", png: "bedrock" },
  { identifier: "bee_nest", png: "bee_nest_front" },
  { identifier: "bee_spawn_egg", png: "egg_bee" },
  { identifier: "beef", png: "beef_raw" },
  { identifier: "beehive", png: "beehive_front" },
  { identifier: "beetroot", png: "beetroot" },
  { identifier: "beetroot_seeds", png: "seeds_beetroot" },
  { identifier: "beetroot_soup", png: "beetroot_soup" },
  { identifier: "bell", png: "villagebell" },
  { identifier: "big_dripleaf", png: "big_dripleaf_top" },
  { identifier: "birch_boat", png: "boat_birch" },
  { identifier: "birch_button", png: "planks_birch" },
  { identifier: "birch_door", png: "door_birch" },
  { identifier: "birch_fence_gate", png: "planks_birch" },
  { identifier: "birch_pressure_plate", png: "planks_birch" },
  { identifier: "birch_sign", png: "sign_birch" },
  { identifier: "birch_stairs", png: "planks_birch" },
  { identifier: "birch_standing_sign", png: "sign_birch" },
  { identifier: "birch_trapdoor", png: "birch_trapdoor" },
  { identifier: "birch_wall_sign", png: "sign_birch" },
  { identifier: "black_dye", png: "dye_powder_black_new" },
  { identifier: "black_glazed_terracotta", png: "glazed_terracotta_black" },
  { identifier: "blackstone", png: "blackstone" },
  { identifier: "blackstone_double_slab", png: "blackstone" },
  { identifier: "blackstone_slab", png: "blackstone" },
  { identifier: "blackstone_stairs", png: "blackstone" },
  { identifier: "blackstone_wall", png: "blackstone" },
  { identifier: "blast_furnace", png: "blast_furnace_front_off" },
  { identifier: "blaze_powder", png: "blaze_powder" },
  { identifier: "blaze_rod", png: "blaze_rod" },
  { identifier: "blaze_spawn_egg", png: "egg_blaze" },
  //{ identifier: "bleach", png: "bleach" },
  { identifier: "blue_dye", png: "dye_powder_blue" },
  { identifier: "blue_glazed_terracotta", png: "glazed_terracotta_blue" },
  { identifier: "blue_ice", png: "blue_ice" },
  { identifier: "boat", png: "boat" },
  { identifier: "bone", png: "bone" },
  { identifier: "bone_block", png: "bone_block_top" },
  { identifier: "bone_meal", png: "dye_powder_white" },
  { identifier: "book", png: "book_normal" },
  { identifier: "bookshelf", png: "bookshelf" },
  { identifier: "border_block", png: "border" },
  { identifier: "bordure_indented_banner_pattern", png: "banner_pattern" },
  { identifier: "bow", png: "bow_standby" },
  { identifier: "bowl", png: "bowl" },
  { identifier: "bread", png: "bread" },
  { identifier: "brewing_stand", png: "brewing_stand" },
  { identifier: "brewingstandblock", png: "brewing_stand_block" },
  { identifier: "brick", png: "brick" },
  { identifier: "brick_block", png: "brick_block" },
  { identifier: "brick_stairs", png: "brick_block" },
  { identifier: "brown_dye", png: "dye_powder_brown_new" },
  { identifier: "brown_glazed_terracotta", png: "glazed_terracotta_brown" },
  { identifier: "brown_mushroom", png: "mushroom_brown" },
  { identifier: "brown_mushroom_block", png: "mushroom_block_skin_brown" },
  { identifier: "bubble_column", png: "water_placeholder" },
  { identifier: "bucket", png: "bucket_empty" },
  { identifier: "budding_amethyst", png: "budding_amethyst" },
  { identifier: "cactus", png: "cactus_side" },
  { identifier: "cake", png: "cake_top" },
  { identifier: "calcite", png: "calcite" },
  { identifier: "camera", png: "camera_front" },
  { identifier: "campfire", png: "campfire" },
  { identifier: "carpet", png: "wool_colored_white" },
  { identifier: "carrot", png: "carrot" },
  { identifier: "carrot_on_a_stick", png: "carrot_on_a_stick" },
  { identifier: "carrots", png: "carrot" },
  { identifier: "cartography_table", png: "cartography_table_top" },
  { identifier: "carved_pumpkin", png: "pumpkin_face_off" },
  { identifier: "cat_spawn_egg", png: "egg_cat" },
  { identifier: "cauldron", png: "cauldron" },
  { identifier: "cave_spider_spawn_egg", png: "egg_cave_spider" },
  { identifier: "cave_vines", png: "cave_vines_body" },
  {
    identifier: "cave_vines_body_with_berries",
    png: "cave_vines_body_berries"
  },
  {
    identifier: "cave_vines_head_with_berries",
    png: "cave_vines_head_berries"
  },
  { identifier: "chain", png: "chain" },
  {
    identifier: "chain_command_block",
    png: "chain_command_block_front_mipmap"
  },
  { identifier: "chainmail_boots", png: "chainmail_boots" },
  { identifier: "chainmail_chestplate", png: "chainmail_chestplate" },
  { identifier: "chainmail_helmet", png: "chainmail_helmet" },
  { identifier: "chainmail_leggings", png: "chainmail_leggings" },
  { identifier: "charcoal", png: "charcoal" },
  //{ identifier: "chemical_heat", png: "chemical_heat" },
  //{ identifier: "chemistry_table", png: "chemistry_table" },
  { identifier: "chest", png: "chest_front" },
  { identifier: "chest_minecart", png: "minecart_chest" },
  { identifier: "chicken", png: "chicken_raw" },
  { identifier: "chicken_spawn_egg", png: "egg_chicken" },
  { identifier: "chiseled_deepslate", png: "chiseled_deepslate" },
  { identifier: "chiseled_nether_bricks", png: "chiseled_nether_bricks" },
  {
    identifier: "chiseled_polished_blackstone",
    png: "chiseled_polished_blackstone"
  },
  { identifier: "chorus_flower", png: "chorus_flower" },
  { identifier: "chorus_fruit", png: "chorus_fruit" },
  { identifier: "chorus_plant", png: "chorus_plant" },
  { identifier: "clay", png: "clay" },
  { identifier: "clay_ball", png: "clay_ball" },
  { identifier: "clock", png: "clock_item" },
  { identifier: "coal", png: "coal" },
  { identifier: "coal_block", png: "coal_block" },
  { identifier: "coal_ore", png: "coal_ore" },
  { identifier: "cobbled_deepslate", png: "cobbled_deepslate" },
  {
    identifier: "cobbled_deepslate",
    png: "cobbled_deepslate"
  },
  { identifier: "cobbled_deepslate_slab", png: "cobbled_deepslate" },
  { identifier: "cobbled_deepslate_stairs", png: "cobbled_deepslate" },
  { identifier: "cobbled_deepslate_wall", png: "cobbled_deepslate" },
  { identifier: "cobblestone", png: "cobblestone" },
  { identifier: "cobblestone_wall", png: "cobblestone" },
  { identifier: "cocoa", png: "cocoa_stage_2" },
  { identifier: "cocoa_beans", png: "dye_powder_brown" },
  { identifier: "cod", png: "fish_raw" },
  { identifier: "cod_bucket", png: "bucket_cod" },
  { identifier: "cod_spawn_egg", png: "egg_cod" },
  //{ identifier: "colored_torch_bp", png: "colored_torch_bp" },
  //{ identifier: "colored_torch_rg", png: "colored_torch_rg" },
  { identifier: "command_block", png: "command_block_front_mipmap" },
  { identifier: "command_block_minecart", png: "minecart_command_block" },
  { identifier: "comparator", png: "comparator" },
  { identifier: "compass", png: "compass_item" },
  { identifier: "composter", png: "composter_side" },
  //{ identifier: "compound", png: "compound" },
  { identifier: "concrete", png: "concrete_white" },
  { identifier: "concrete_powder", png: "concrete_powder_white" },
  { identifier: "conduit", png: "conduit_open" },
  { identifier: "cooked_beef", png: "beef_cooked" },
  { identifier: "cooked_chicken", png: "chicken_cooked" },
  { identifier: "cooked_cod", png: "fish_cooked" },
  { identifier: "cooked_mutton", png: "mutton_cooked" },
  { identifier: "cooked_porkchop", png: "porkchop_cooked" },
  { identifier: "cooked_rabbit", png: "rabbit_cooked" },
  { identifier: "cooked_salmon", png: "fish_salmon_cooked" },
  { identifier: "cookie", png: "cookie" },
  { identifier: "copper_block", png: "copper_block" },
  { identifier: "copper_ingot", png: "copper_ingot" },
  { identifier: "copper_ore", png: "copper_ore" },
  { identifier: "coral", png: "coral_blue" },
  { identifier: "coral_block", png: "coral_blue" },
  { identifier: "coral_fan", png: "coral_fan_blue" },
  { identifier: "coral_fan_dead", png: "coral_fan_blue_dead" },
  { identifier: "coral_fan_hang", png: "coral_fan_blue" },
  { identifier: "coral_fan_hang2", png: "coral_fan_blue" },
  { identifier: "coral_fan_hang3", png: "coral_fan_blue" },
  { identifier: "cow_spawn_egg", png: "egg_cow" },
  { identifier: "cracked_deepslate_bricks", png: "cracked_deepslate_bricks" },
  { identifier: "cracked_deepslate_tiles", png: "cracked_deepslate_tiles" },
  { identifier: "cracked_nether_bricks", png: "cracked_nether_bricks" },
  {
    identifier: "cracked_polished_blackstone_bricks",
    png: "cracked_polished_blackstone_bricks"
  },
  { identifier: "crafting_table", png: "crafting_table_side" },
  { identifier: "creeper_banner_pattern", png: "banner_pattern" },
  { identifier: "creeper_spawn_egg", png: "egg_creeper" },
  { identifier: "crimson_button", png: "crimson_planks" },
  { identifier: "crimson_door", png: "crimson_door" },
  { identifier: "crimson_double_slab", png: "crimson_planks" },
  { identifier: "crimson_fence", png: "crimson_planks" },
  { identifier: "crimson_fence_gate", png: "crimson_planks" },
  { identifier: "crimson_fungus", png: "crimson_fungus" },
  { identifier: "crimson_hyphae", png: "crimson_log_side" },
  { identifier: "crimson_nylium", png: "crimson_nylium_side" },
  { identifier: "crimson_planks", png: "crimson_planks" },
  { identifier: "crimson_pressure_plate", png: "crimson_planks" },
  { identifier: "crimson_roots", png: "crimson_roots" },
  { identifier: "crimson_sign", png: "sign_crimson" },
  { identifier: "crimson_slab", png: "crimson_planks" },
  { identifier: "crimson_stairs", png: "crimson_planks" },
  { identifier: "crimson_standing_sign", png: "sign_crimson" },
  { identifier: "crimson_stem", png: "crimson_log_top" },
  { identifier: "crimson_trapdoor", png: "crimson_trapdoor" },
  { identifier: "crimson_wall_sign", png: "sign_crimson" },
  { identifier: "crossbow", png: "crossbow_pulling_0" },
  { identifier: "crying_obsidian", png: "crying_obsidian" },
  { identifier: "cut_copper", png: "cut_copper" },
  { identifier: "cut_copper_slab", png: "cut_copper" },
  { identifier: "cut_copper_stairs", png: "cut_copper" },
  { identifier: "cyan_dye", png: "dye_powder_cyan" },
  { identifier: "cyan_glazed_terracotta", png: "glazed_terracotta_cyan" },
  { identifier: "dark_oak_boat", png: "boat_darkoak" },
  { identifier: "dark_oak_button", png: "planks_big_oak" },
  { identifier: "dark_oak_door", png: "door_dark_oak" },
  { identifier: "dark_oak_fence_gate", png: "planks_big_oak" },
  { identifier: "dark_oak_pressure_plate", png: "planks_big_oak" },
  { identifier: "dark_oak_sign", png: "sign_darkoak" },
  { identifier: "dark_oak_stairs", png: "planks_big_oak" },
  { identifier: "dark_oak_trapdoor", png: "dark_oak_trapdoor" },
  { identifier: "dark_prismarine_stairs", png: "prismarine_dark" },
  { identifier: "darkoak_standing_sign", png: "sign_darkoak" },
  { identifier: "darkoak_wall_sign", png: "sign_darkoak" },
  { identifier: "daylight_detector", png: "daylight_detector_top" },
  { identifier: "daylight_detector_inverted", png: "daylight_detector_inverted_top" },
  { identifier: "deadbush", png: "deadbush" },
  { identifier: "debug_stick", png: "stick" },
  { identifier: "deepslate", png: "deepslate" },
  {
    identifier: "deepslate_brick_double_slab",
    png: "deepslate_bricks"
  },
  { identifier: "deepslate_brick_slab", png: "deepslate_bricks" },
  { identifier: "deepslate_brick_stairs", png: "deepslate_bricks" },
  { identifier: "deepslate_brick_wall", png: "deepslate_bricks" },
  { identifier: "deepslate_bricks", png: "deepslate_bricks" },
  { identifier: "deepslate_coal_ore", png: "deepslate_coal_ore" },
  { identifier: "deepslate_copper_ore", png: "deepslate_copper_ore" },
  { identifier: "deepslate_diamond_ore", png: "deepslate_diamond_ore" },
  { identifier: "deepslate_emerald_ore", png: "deepslate_emerald_ore" },
  { identifier: "deepslate_gold_ore", png: "deepslate_gold_ore" },
  { identifier: "deepslate_iron_ore", png: "deepslate_iron_ore" },
  { identifier: "deepslate_lapis_ore", png: "deepslate_lapis_ore" },
  { identifier: "deepslate_redstone_ore", png: "deepslate_redstone_ore" },
  { identifier: "deepslate_tile_double_slab", png: "deepslate_tiles" },
  { identifier: "deepslate_tile_slab", png: "deepslate_tiles" },
  { identifier: "deepslate_tile_stairs", png: "deepslate_tiles" },
  { identifier: "deepslate_tile_wall", png: "deepslate_tiles" },
  { identifier: "deepslate_tiles", png: "deepslate_tiles" },
  { identifier: "deny", png: "build_deny" },
  { identifier: "detector_rail", png: "rail_detector" },
  { identifier: "diamond", png: "diamond" },
  { identifier: "diamond_axe", png: "diamond_axe" },
  { identifier: "diamond_block", png: "diamond_block" },
  { identifier: "diamond_boots", png: "diamond_boots" },
  { identifier: "diamond_chestplate", png: "diamond_chestplate" },
  { identifier: "diamond_helmet", png: "diamond_helmet" },
  { identifier: "diamond_hoe", png: "diamond_hoe" },
  { identifier: "diamond_horse_armor", png: "diamond_horse_armor" },
  { identifier: "diamond_leggings", png: "diamond_leggings" },
  { identifier: "diamond_ore", png: "diamond_ore" },
  { identifier: "diamond_pickaxe", png: "diamond_pickaxe" },
  { identifier: "diamond_shovel", png: "diamond_shovel" },
  { identifier: "diamond_sword", png: "diamond_sword" },
  { identifier: "diorite_stairs", png: "stone_diorite" },
  { identifier: "dirt", png: "dirt" },
  { identifier: "dirt_with_roots", png: "dirt_with_roots" },
  { identifier: "dispenser", png: "dispenser_front_horizontal" },
  { identifier: "dolphin_spawn_egg", png: "egg_dolphin" },
  { identifier: "donkey_spawn_egg", png: "egg_donkey" },
  { identifier: "double_cut_copper_slab", png: "cut_copper" },
  { identifier: "double_plant", png: "double_plant_grass_carried" },
  { identifier: "double_stone_slab", png: "stone" },
  { identifier: "double_stone_slab2", png: "stone" },
  { identifier: "double_stone_slab3", png: "stone" },
  { identifier: "double_stone_slab4", png: "stone" },
  { identifier: "double_wooden_slab", png: "planks_oak" },
  { identifier: "dragon_breath", png: "dragons_breath" },
  { identifier: "dragon_egg", png: "dragon_egg" },
  { identifier: "dried_kelp", png: "dried_kelp" },
  { identifier: "dried_kelp_block", png: "dried_kelp_top" },
  { identifier: "dripstone_block", png: "dripstone_block" },
  { identifier: "dropper", png: "dropper_front_horizontal" },
  { identifier: "drowned_spawn_egg", png: "egg_drowned" },
  { identifier: "dye", png: "dye_powder_white_new" },
  { identifier: "egg", png: "egg" },
  { identifier: "elder_guardian_spawn_egg", png: "egg_elderguardian" },
  /*{ identifier: "element_0", png: "element_0" },
  { identifier: "element_1", png: "element_1" },
  { identifier: "element_10", png: "element_10" },
  { identifier: "element_100", png: "element_100" },
  { identifier: "element_101", png: "element_101" },
  { identifier: "element_102", png: "element_102" },
  { identifier: "element_103", png: "element_103" },
  { identifier: "element_104", png: "element_104" },
  { identifier: "element_105", png: "element_105" },
  { identifier: "element_106", png: "element_106" },
  { identifier: "element_107", png: "element_107" },
  { identifier: "element_108", png: "element_108" },
  { identifier: "element_109", png: "element_109" },
  { identifier: "element_11", png: "element_11" },
  { identifier: "element_110", png: "element_110" },
  { identifier: "element_111", png: "element_111" },
  { identifier: "element_112", png: "element_112" },
  { identifier: "element_113", png: "element_113" },
  { identifier: "element_114", png: "element_114" },
  { identifier: "element_115", png: "element_115" },
  { identifier: "element_116", png: "element_116" },
  { identifier: "element_117", png: "element_117" },
  { identifier: "element_118", png: "element_118" },
  { identifier: "element_12", png: "element_12" },
  { identifier: "element_13", png: "element_13" },
  { identifier: "element_14", png: "element_14" },
  { identifier: "element_15", png: "element_15" },
  { identifier: "element_16", png: "element_16" },
  { identifier: "element_17", png: "element_17" },
  { identifier: "element_18", png: "element_18" },
  { identifier: "element_19", png: "element_19" },
  { identifier: "element_2", png: "element_2" },
  { identifier: "element_20", png: "element_20" },
  { identifier: "element_21", png: "element_21" },
  { identifier: "element_22", png: "element_22" },
  { identifier: "element_23", png: "element_23" },
  { identifier: "element_24", png: "element_24" },
  { identifier: "element_25", png: "element_25" },
  { identifier: "element_26", png: "element_26" },
  { identifier: "element_27", png: "element_27" },
  { identifier: "element_28", png: "element_28" },
  { identifier: "element_29", png: "element_29" },
  { identifier: "element_3", png: "element_3" },
  { identifier: "element_30", png: "element_30" },
  { identifier: "element_31", png: "element_31" },
  { identifier: "element_32", png: "element_32" },
  { identifier: "element_33", png: "element_33" },
  { identifier: "element_34", png: "element_34" },
  { identifier: "element_35", png: "element_35" },
  { identifier: "element_36", png: "element_36" },
  { identifier: "element_37", png: "element_37" },
  { identifier: "element_38", png: "element_38" },
  { identifier: "element_39", png: "element_39" },
  { identifier: "element_4", png: "element_4" },
  { identifier: "element_40", png: "element_40" },
  { identifier: "element_41", png: "element_41" },
  { identifier: "element_42", png: "element_42" },
  { identifier: "element_43", png: "element_43" },
  { identifier: "element_44", png: "element_44" },
  { identifier: "element_45", png: "element_45" },
  { identifier: "element_46", png: "element_46" },
  { identifier: "element_47", png: "element_47" },
  { identifier: "element_48", png: "element_48" },
  { identifier: "element_49", png: "element_49" },
  { identifier: "element_5", png: "element_5" },
  { identifier: "element_50", png: "element_50" },
  { identifier: "element_51", png: "element_51" },
  { identifier: "element_52", png: "element_52" },
  { identifier: "element_53", png: "element_53" },
  { identifier: "element_54", png: "element_54" },
  { identifier: "element_55", png: "element_55" },
  { identifier: "element_56", png: "element_56" },
  { identifier: "element_57", png: "element_57" },
  { identifier: "element_58", png: "element_58" },
  { identifier: "element_59", png: "element_59" },
  { identifier: "element_6", png: "element_6" },
  { identifier: "element_60", png: "element_60" },
  { identifier: "element_61", png: "element_61" },
  { identifier: "element_62", png: "element_62" },
  { identifier: "element_63", png: "element_63" },
  { identifier: "element_64", png: "element_64" },
  { identifier: "element_65", png: "element_65" },
  { identifier: "element_66", png: "element_66" },
  { identifier: "element_67", png: "element_67" },
  { identifier: "element_68", png: "element_68" },
  { identifier: "element_69", png: "element_69" },
  { identifier: "element_7", png: "element_7" },
  { identifier: "element_70", png: "element_70" },
  { identifier: "element_71", png: "element_71" },
  { identifier: "element_72", png: "element_72" },
  { identifier: "element_73", png: "element_73" },
  { identifier: "element_74", png: "element_74" },
  { identifier: "element_75", png: "element_75" },
  { identifier: "element_76", png: "element_76" },
  { identifier: "element_77", png: "element_77" },
  { identifier: "element_78", png: "element_78" },
  { identifier: "element_79", png: "element_79" },
  { identifier: "element_8", png: "element_8" },
  { identifier: "element_80", png: "element_80" },
  { identifier: "element_81", png: "element_81" },
  { identifier: "element_82", png: "element_82" },
  { identifier: "element_83", png: "element_83" },
  { identifier: "element_84", png: "element_84" },
  { identifier: "element_85", png: "element_85" },
  { identifier: "element_86", png: "element_86" },
  { identifier: "element_87", png: "element_87" },
  { identifier: "element_88", png: "element_88" },
  { identifier: "element_89", png: "element_89" },
  { identifier: "element_9", png: "element_9" },
  { identifier: "element_90", png: "element_90" },
  { identifier: "element_91", png: "element_91" },
  { identifier: "element_92", png: "element_92" },
  { identifier: "element_93", png: "element_93" },
  { identifier: "element_94", png: "element_94" },
  { identifier: "element_95", png: "element_95" },
  { identifier: "element_96", png: "element_96" },
  { identifier: "element_97", png: "element_97" },
  { identifier: "element_98", png: "element_98" },
  { identifier: "element_99", png: "element_99" },*/
  { identifier: "elytra", png: "elytra" },
  { identifier: "emerald", png: "emerald" },
  { identifier: "emerald_block", png: "emerald_block" },
  { identifier: "emerald_ore", png: "emerald_ore" },
  { identifier: "empty_map", png: "map_empty" },
  { identifier: "enchanted_book", png: "book_enchanted" },
  { identifier: "enchanted_golden_apple", png: "apple_golden" },
  { identifier: "enchanting_table", png: "enchanting_table_side" },
  { identifier: "end_brick_stairs", png: "end_bricks" },
  { identifier: "end_bricks", png: "end_bricks" },
  { identifier: "end_crystal", png: "end_crystal" },
  { identifier: "end_gateway", png: "end_gateway" },
  { identifier: "end_portal", png: "end_portal" },
  { identifier: "end_portal_frame", png: "endframe_top" },
  { identifier: "end_rod", png: "end_rod" },
  { identifier: "end_stone", png: "end_stone" },
  { identifier: "ender_chest", png: "ender_chest_front" },
  { identifier: "ender_eye", png: "ender_eye" },
  { identifier: "ender_pearl", png: "ender_pearl" },
  { identifier: "enderman_spawn_egg", png: "egg_enderman" },
  { identifier: "endermite_spawn_egg", png: "egg_endermite" },
  { identifier: "evoker_spawn_egg", png: "egg_evoker" },
  { identifier: "experience_bottle", png: "experience_bottle" },
  { identifier: "exposed_copper", png: "exposed_copper" },
  { identifier: "exposed_cut_copper", png: "exposed_cut_copper" },
  { identifier: "exposed_cut_copper_slab", png: "exposed_cut_copper" },
  { identifier: "exposed_cut_copper_stairs", png: "exposed_cut_copper" },
  {
    identifier: "exposed_double_cut_copper_slab",
    png: "exposed_cut_copper"
  },
  { identifier: "farmland", png: "farmland_dry" },
  { identifier: "feather", png: "feather" },
  { identifier: "fence", png: "planks_oak" },
  { identifier: "fence_gate", png: "planks_oak" },
  { identifier: "fermented_spider_eye", png: "spider_eye_fermented" },
  { identifier: "field_masoned_banner_pattern", png: "banner_pattern" },
  { identifier: "filled_map", png: "map_filled" },
  { identifier: "fire", png: "fire_0_placeholder" },
  { identifier: "fire_charge", png: "fireball" },
  { identifier: "firework_rocket", png: "fireworks" },
  { identifier: "firework_star", png: "fireworks" },
  { identifier: "fishing_rod", png: "fishing_rod_uncast" },
  { identifier: "fletching_table", png: "fletcher_table_side1" },
  { identifier: "flint", png: "flint" },
  { identifier: "flint_and_steel", png: "flint_and_steel" },
  { identifier: "flower_banner_pattern", png: "banner_pattern" },
  { identifier: "flower_pot", png: "flower_pot" },
  { identifier: "flowering_azalea", png: "azalea_leaves_flowers_opaque" },
  { identifier: "flowing_lava", png: "lava_placeholder" },
  { identifier: "flowing_water", png: "water_placeholder" },
  { identifier: "fox_spawn_egg", png: "egg_fox" },
  { identifier: "frame", png: "item_frame" },
  { identifier: "frosted_ice", png: "frosted_ice_3" },
  { identifier: "furnace", png: "furnace_front_off" },
  { identifier: "ghast_spawn_egg", png: "egg_ghast" },
  { identifier: "ghast_tear", png: "ghast_tear" },
  { identifier: "gilded_blackstone", png: "gilded_blackstone" },
  { identifier: "glass", png: "glass" },
  { identifier: "glass_bottle", png: "potion_bottle_empty" },
  { identifier: "glass_pane", png: "glass" },
  { identifier: "glistering_melon_slice", png: "melon_speckled" },
  { identifier: "glow_frame", png: "glow_item_frame" },
  { identifier: "glow_ink_sac", png: "dye_powder_glow" },
  { identifier: "glow_lichen", png: "glow_lichen" },
  { identifier: "glow_squid_spawn_egg", png: "egg_glow_squid" },
  //{ identifier: "glow_stick", png: "glowstone" },
  { identifier: "glowingobsidian", png: "glowing_obsidian" },
  { identifier: "glowstone", png: "glowstone" },
  { identifier: "glowstone_dust", png: "glowstone_dust" },
  { identifier: "goat_horn", png: "villagebell" },
  { identifier: "goat_spawn_egg", png: "egg_null" },
  { identifier: "gold_block", png: "gold_block" },
  { identifier: "gold_ingot", png: "gold_ingot" },
  { identifier: "gold_nugget", png: "gold_nugget" },
  { identifier: "gold_ore", png: "gold_ore" },
  { identifier: "golden_apple", png: "apple_golden" },
  { identifier: "golden_axe", png: "gold_axe" },
  { identifier: "golden_boots", png: "gold_boots" },
  { identifier: "golden_carrot", png: "carrot_golden" },
  { identifier: "golden_chestplate", png: "gold_chestplate" },
  { identifier: "golden_helmet", png: "gold_helmet" },
  { identifier: "golden_hoe", png: "gold_hoe" },
  { identifier: "golden_horse_armor", png: "gold_horse_armor" },
  { identifier: "golden_leggings", png: "gold_leggings" },
  { identifier: "golden_pickaxe", png: "gold_pickaxe" },
  { identifier: "golden_rail", png: "rail_golden" },
  { identifier: "golden_shovel", png: "gold_shovel" },
  { identifier: "golden_sword", png: "gold_sword" },
  { identifier: "granite_stairs", png: "stone_granite" },
  { identifier: "grass", png: "grass_side_carried" },
  { identifier: "grass_path", png: "grass_path_side" },
  { identifier: "gravel", png: "gravel" },
  { identifier: "gray_dye", png: "dye_powder_gray" },
  { identifier: "gray_glazed_terracotta", png: "glazed_terracotta_gray" },
  { identifier: "green_dye", png: "dye_powder_green" },
  { identifier: "green_glazed_terracotta", png: "glazed_terracotta_green" },
  { identifier: "grindstone", png: "stone_slab_top" },
  { identifier: "guardian_spawn_egg", png: "egg_guardian" },
  { identifier: "gunpowder", png: "gunpowder" },
  { identifier: "hanging_roots", png: "hanging_roots" },
  { identifier: "hard_glass", png: "glass" },
  { identifier: "hard_glass_pane", png: "glass" },
  { identifier: "hard_stained_glass", png: "glass" },
  { identifier: "hard_stained_glass_pane", png: "glass" },
  { identifier: "hardened_clay", png: "hardened_clay" },
  { identifier: "hay_block", png: "hay_block_side" },
  { identifier: "heart_of_the_sea", png: "heartofthesea_closed" },
  { identifier: "heavy_weighted_pressure_plate", png: "iron_block" },
  { identifier: "hoglin_spawn_egg", png: "egg_pig" },
  { identifier: "honey_block", png: "honey_bottom" },
  { identifier: "honey_bottle", png: "honey_bottle" },
  { identifier: "honeycomb", png: "honeycomb" },
  { identifier: "honeycomb_block", png: "honeycomb_block" },
  { identifier: "hopper", png: "hopper" },
  { identifier: "hopper_minecart", png: "minecart_hopper" },
  { identifier: "horse_spawn_egg", png: "egg_horse" },
  { identifier: "husk_spawn_egg", png: "egg_husk" },
  { identifier: "ice", png: "ice" },
  //{ identifier: "ice_bomb", png: "ice" },
  { identifier: "infested_deepslate", png: "deepslate" },
  { identifier: "info_update", png: "missing_tile" },
  { identifier: "info_update2", png: "missing_tile" },
  { identifier: "ink_sac", png: "dye_powder_black" },
  { identifier: "invisiblebedrock", png: "stone" },
  { identifier: "iron_axe", png: "iron_axe" },
  { identifier: "iron_bars", png: "iron_bars" },
  { identifier: "iron_block", png: "iron_block" },
  { identifier: "iron_boots", png: "iron_boots" },
  { identifier: "iron_chestplate", png: "iron_chestplate" },
  { identifier: "iron_door", png: "door_iron" },
  { identifier: "iron_helmet", png: "iron_helmet" },
  { identifier: "iron_hoe", png: "iron_hoe" },
  { identifier: "iron_horse_armor", png: "iron_horse_armor" },
  { identifier: "iron_ingot", png: "iron_ingot" },
  { identifier: "iron_leggings", png: "iron_leggings" },
  { identifier: "iron_nugget", png: "iron_nugget" },
  { identifier: "iron_ore", png: "iron_ore" },
  { identifier: "iron_pickaxe", png: "iron_pickaxe" },
  { identifier: "iron_shovel", png: "iron_shovel" },
  { identifier: "iron_sword", png: "iron_sword" },
  { identifier: "iron_trapdoor", png: "iron_trapdoor" },
  /*{ identifier: "item.acacia_door", png: "item.acacia_door" },
  { identifier: "item.bed", png: "item.bed" },
  { identifier: "item.beetroot", png: "item.beetroot" },
  { identifier: "item.birch_door", png: "item.birch_door" },
  { identifier: "item.cake", png: "item.cake" },
  { identifier: "item.camera", png: "item.camera" },
  { identifier: "item.campfire", png: "item.campfire" },
  { identifier: "item.cauldron", png: "item.cauldron" },
  { identifier: "item.chain", png: "item.chain" },
  { identifier: "item.crimson_door", png: "item.crimson_door" },
  { identifier: "item.dark_oak_door", png: "item.dark_oak_door" },
  { identifier: "item.flower_pot", png: "item.flower_pot" },
  { identifier: "item.frame", png: "item.frame" },
  { identifier: "item.glow_frame", png: "item.glow_frame" },
  { identifier: "item.hopper", png: "item.hopper" },
  { identifier: "item.iron_door", png: "item.iron_door" },
  { identifier: "item.jungle_door", png: "item.jungle_door" },
  { identifier: "item.kelp", png: "item.kelp" },
  { identifier: "item.nether_sprouts", png: "item.nether_sprouts" },
  { identifier: "item.nether_wart", png: "item.nether_wart" },
  { identifier: "item.reeds", png: "item.reeds" },
  { identifier: "item.skull", png: "item.skull" },
  { identifier: "item.soul_campfire", png: "item.soul_campfire" },
  { identifier: "item.spruce_door", png: "item.spruce_door" },
  { identifier: "item.warped_door", png: "item.warped_door" },
  { identifier: "item.wheat", png: "item.wheat" },
  { identifier: "item.wooden_door", png: "item.wooden_door" },*/
  { identifier: "jigsaw", png: "jigsaw_front" },
  { identifier: "jukebox", png: "jukebox_top" },
  { identifier: "jungle_boat", png: "boat_jungle" },
  { identifier: "jungle_button", png: "planks_jungle" },
  { identifier: "jungle_door", png: "door_jungle" },
  { identifier: "jungle_fence_gate", png: "planks_jungle" },
  { identifier: "jungle_pressure_plate", png: "planks_jungle" },
  { identifier: "jungle_sign", png: "sign_jungle" },
  { identifier: "jungle_stairs", png: "planks_jungle" },
  { identifier: "jungle_standing_sign", png: "sign_jungle" },
  { identifier: "jungle_trapdoor", png: "jungle_trapdoor" },
  { identifier: "jungle_wall_sign", png: "sign_jungle" },
  { identifier: "kelp", png: "kelp" },
  { identifier: "ladder", png: "ladder" },
  { identifier: "lantern", png: "lantern" },
  { identifier: "lapis_block", png: "lapis_block" },
  { identifier: "lapis_lazuli", png: "dye_powder_blue" },
  { identifier: "lapis_ore", png: "lapis_ore" },
  { identifier: "large_amethyst_bud", png: "large_amethyst_bud" },
  { identifier: "lava", png: "lava_placeholder" },
  { identifier: "lava_bucket", png: "bucket_lava" },
  { identifier: "lava_cauldron", png: "cauldron_side" },
  { identifier: "lead", png: "lead" },
  { identifier: "leather", png: "leather" },
  { identifier: "leather_boots", png: "leather" },
  { identifier: "leather_chestplate", png: "leather" },
  { identifier: "leather_helmet", png: "leather" },
  { identifier: "leather_horse_armor", png: "leather" },
  { identifier: "leather_leggings", png: "leather" },
  { identifier: "leaves", png: "grass_carried" },
  { identifier: "leaves2", png: "grass_carried" },
  { identifier: "lectern", png: "lectern_top" },
  { identifier: "lever", png: "lever" },
  { identifier: "light_block", png: "light_block_0" },
  { identifier: "light_blue_dye", png: "dye_powder_light_blue" },
  { identifier: "light_blue_glazed_terracotta", png: "glazed_terracotta_light_blue" },
  { identifier: "light_gray_dye", png: "dye_powder_silver" },
  { identifier: "light_weighted_pressure_plate", png: "gold_block" },
  { identifier: "lightning_rod", png: "lightning_rod" },
  { identifier: "lime_dye", png: "dye_powder_lime" },
  { identifier: "lime_glazed_terracotta", png: "glazed_terracotta_lime" },
  { identifier: "lingering_potion", png: "potion_bottle_lingering" },
  { identifier: "lit_blast_furnace", png: "blast_furnace_side" },
  {
    identifier: "lit_deepslate_redstone_ore",
    png: "deepslate_redstone_ore"
  },
  { identifier: "lit_furnace", png: "furnace_front_on" },
  { identifier: "lit_pumpkin", png: "pumpkin_face_off" },
  { identifier: "lit_redstone_lamp", png: "redstone_lamp_on" },
  { identifier: "lit_redstone_ore", png: "redstone_ore" },
  { identifier: "lit_smoker", png: "smoker_front_on" },
  { identifier: "llama_spawn_egg", png: "egg_llama" },
  { identifier: "lodestone", png: "lodestone_side" },
  { identifier: "lodestone_compass", png: "lodestonecompass_item" },
  { identifier: "log", png: "log_oak" },
  { identifier: "log2", png: "log_oak" },
  { identifier: "loom", png: "loom_top" },
  { identifier: "magenta_dye", png: "dye_powder_magenta" },
  { identifier: "magenta_glazed_terracotta", png: "glazed_terracotta_magenta" },
  { identifier: "magma", png: "magma" },
  { identifier: "magma_cream", png: "magma_cream" },
  { identifier: "magma_cube_spawn_egg", png: "egg_slime" },
  //{ identifier: "medicine", png: "medicine" },
  { identifier: "medium_amethyst_bud", png: "medium_amethyst_bud" },
  { identifier: "melon_block", png: "melon_side" },
  { identifier: "melon_seeds", png: "seeds_melon" },
  { identifier: "melon_slice", png: "melon" },
  { identifier: "melon_stem", png: "melon_stem_connected" },
  { identifier: "milk_bucket", png: "bucket_milk" },
  { identifier: "minecart", png: "minecart_normal" },
  { identifier: "mob_spawner", png: "mob_spawner" },
  { identifier: "mojang_banner_pattern", png: "banner_pattern" },
  { identifier: "monster_egg", png: "stone" },
  { identifier: "mooshroom_spawn_egg", png: "egg_chicken" },
  { identifier: "moss_block", png: "moss_block" },
  { identifier: "moss_carpet", png: "moss_block" },
  { identifier: "mossy_cobblestone", png: "cobblestone_mossy" },
  { identifier: "mossy_cobblestone_stairs", png: "cobblestone_mossy" },
  { identifier: "mossy_stone_brick_stairs", png: "stonebrick_mossy" },
  { identifier: "movingblock", png: "stone" },
  { identifier: "mule_spawn_egg", png: "egg_mule" },
  { identifier: "mushroom_stew", png: "mushroom_stew" },
  { identifier: "music_disc_11", png: "record_11" },
  { identifier: "music_disc_13", png: "record_13" },
  { identifier: "music_disc_blocks", png: "record_blocks" },
  { identifier: "music_disc_cat", png: "record_cat" },
  { identifier: "music_disc_chirp", png: "record_chirp" },
  { identifier: "music_disc_far", png: "record_far" },
  { identifier: "music_disc_mall", png: "record_mall" },
  { identifier: "music_disc_mellohi", png: "record_mellohi" },
  { identifier: "music_disc_pigstep", png: "record_pigstep" },
  { identifier: "music_disc_stal", png: "record_stal" },
  { identifier: "music_disc_strad", png: "record_strad" },
  { identifier: "music_disc_wait", png: "record_wait" },
  { identifier: "music_disc_ward", png: "record_ward" },
  { identifier: "mutton", png: "mutton_raw" },
  { identifier: "mycelium", png: "mycelium_side" },
  { identifier: "name_tag", png: "name_tag" },
  { identifier: "nautilus_shell", png: "nautilus" },
  { identifier: "nether_brick", png: "netherbrick" },
  { identifier: "nether_brick_fence", png: "nether_brick" },
  { identifier: "nether_brick_stairs", png: "nether_brick" },
  { identifier: "nether_gold_ore", png: "nether_gold_ore" },
  { identifier: "nether_sprouts", png: "nether_sprouts" },
  { identifier: "nether_star", png: "nether_star" },
  { identifier: "nether_wart", png: "nether_wart_stage_2" },
  { identifier: "nether_wart_block", png: "nether_wart_block" },
  { identifier: "netherbrick", png: "nether_brick" },
  { identifier: "netherite_axe", png: "netherite_axe" },
  { identifier: "netherite_block", png: "netherite_block" },
  { identifier: "netherite_boots", png: "netherite_boots" },
  { identifier: "netherite_chestplate", png: "netherite_chestplate" },
  { identifier: "netherite_helmet", png: "netherite_helmet" },
  { identifier: "netherite_hoe", png: "netherite_hoe" },
  { identifier: "netherite_ingot", png: "netherite_ingot" },
  { identifier: "netherite_leggings", png: "netherite_leggings" },
  { identifier: "netherite_pickaxe", png: "netherite_pickaxe" },
  { identifier: "netherite_scrap", png: "netherite_scrap" },
  { identifier: "netherite_shovel", png: "netherite_shovel" },
  { identifier: "netherite_sword", png: "netherite_sword" },
  { identifier: "netherrack", png: "netherrack" },
  { identifier: "netherreactor", png: "reactor_core_stage_0" },
  { identifier: "normal_stone_stairs", png: "stone" },
  { identifier: "noteblock", png: "noteblock" },
  { identifier: "npc_spawn_egg", png: "egg_npc" },
  { identifier: "oak_boat", png: "boat_oak" },
  { identifier: "oak_sign", png: "sign" },
  { identifier: "oak_stairs", png: "planks_oak" },
  { identifier: "observer", png: "observer_front" },
  { identifier: "obsidian", png: "obsidian" },
  { identifier: "ocelot_spawn_egg", png: "egg_ocelot" },
  { identifier: "orange_dye", png: "dye_powder_orange" },
  { identifier: "orange_glazed_terracotta", png: "glazed_terracotta_orange" },
  { identifier: "oxidized_copper", png: "oxidized_copper" },
  { identifier: "oxidized_cut_copper", png: "oxidized_cut_copper" },
  { identifier: "oxidized_cut_copper_slab", png: "oxidized_cut_copper" },
  {
    identifier: "oxidized_cut_copper_stairs",
    png: "oxidized_cut_copper"
  },
  {
    identifier: "oxidized_double_cut_copper_slab",
    png: "oxidized_cut_copper"
  },
  { identifier: "packed_ice", png: "ice_packed" },
  { identifier: "painting", png: "painting" },
  { identifier: "panda_spawn_egg", png: "egg_panda" },
  { identifier: "paper", png: "paper" },
  { identifier: "parrot_spawn_egg", png: "egg_parrot" },
  { identifier: "phantom_membrane", png: "phantom_membrane" },
  { identifier: "phantom_spawn_egg", png: "egg_phantom" },
  { identifier: "pig_spawn_egg", png: "egg_pig" },
  { identifier: "piglin_banner_pattern", png: "banner_pattern" },
  { identifier: "piglin_brute_spawn_egg", png: "egg_pigzombie" },
  { identifier: "piglin_spawn_egg", png: "egg_pigzombie" },
  { identifier: "pillager_spawn_egg", png: "egg_pillager" },
  { identifier: "pink_dye", png: "dye_powder_pink" },
  { identifier: "pink_glazed_terracotta", png: "glazed_terracotta_pink" },
  { identifier: "piston", png: "piston_side" },
  { identifier: "pistonarmcollision", png: "piston_side" },
  { identifier: "planks", png: "planks_oak" },
  { identifier: "podzol", png: "dirt_podzol_side" },
  { identifier: "pointed_dripstone", png: "pointed_dripstone_up_tip" },
  { identifier: "poisonous_potato", png: "potato_poisonous" },
  { identifier: "polar_bear_spawn_egg", png: "egg_polarbear" },
  { identifier: "polished_andesite_stairs", png: "stone_andesite_smooth" },
  { identifier: "polished_basalt", png: "polished_basalt_side" },
  { identifier: "polished_blackstone", png: "polished_blackstone" },
  {
    identifier: "polished_blackstone_brick_double_slab",
    png: "polished_blackstone_bricks"
  },
  {
    identifier: "polished_blackstone_brick_slab",
    png: "polished_blackstone_bricks"
  },
  {
    identifier: "polished_blackstone_brick_stairs",
    png: "polished_blackstone_bricks"
  },
  {
    identifier: "polished_blackstone_brick_wall",
    png: "polished_blackstone_bricks"
  },
  {
    identifier: "polished_blackstone_bricks",
    png: "polished_blackstone_bricks"
  },
  { identifier: "polished_blackstone_button", png: "polished_blackstone" },
  { identifier: "polished_blackstone_double_slab", png: "polished_blackstone" },
  {
    identifier: "polished_blackstone_pressure_plate",
    png: "polished_blackstone"
  },
  { identifier: "polished_blackstone_slab", png: "polished_blackstone" },
  { identifier: "polished_blackstone_stairs", png: "polished_blackstone" },
  { identifier: "polished_blackstone_wall", png: "polished_blackstone" },
  { identifier: "polished_deepslate", png: "polished_deepslate" },
  {
    identifier: "polished_deepslate_double_slab",
    png: "polished_deepslate"
  },
  { identifier: "polished_deepslate_slab", png: "polished_deepslate" },
  { identifier: "polished_deepslate_stairs", png: "polished_deepslate" },
  { identifier: "polished_deepslate_wall", png: "polished_deepslate" },
  { identifier: "polished_diorite_stairs", png: "stone_diorite_smooth" },
  { identifier: "polished_granite_stairs", png: "stone_granite_smooth" },
  { identifier: "popped_chorus_fruit", png: "chorus_fruit_popped" },
  { identifier: "porkchop", png: "porkchop_cooked" },
  { identifier: "portal", png: "portal_placeholder" },
  { identifier: "potato", png: "potato" },
  { identifier: "potatoes", png: "potato" },
  { identifier: "potion", png: "potion_bottle_drinkable" },
  { identifier: "powder_snow", png: "powder_snow" },
  { identifier: "powder_snow_bucket", png: "bucket_powder_snow" },
  { identifier: "powered_comparator", png: "comparator_on" },
  { identifier: "powered_repeater", png: "repeater_on" },
  { identifier: "prismarine", png: "prismarine_bricks" },
  { identifier: "prismarine_bricks_stairs", png: "prismarine_bricks" },
  { identifier: "prismarine_crystals", png: "prismarine_crystals" },
  { identifier: "prismarine_shard", png: "prismarine_shard" },
  { identifier: "prismarine_stairs", png: "prismarine_bricks" },
  { identifier: "pufferfish", png: "fish_pufferfish_raw" },
  { identifier: "pufferfish_bucket", png: "bucket_pufferfish" },
  { identifier: "pufferfish_spawn_egg", png: "egg_pufferfish" },
  { identifier: "pumpkin", png: "pumpkin_side" },
  { identifier: "pumpkin_pie", png: "pumpkin_pie" },
  { identifier: "pumpkin_seeds", png: "seeds_pumpkin" },
  { identifier: "pumpkin_stem", png: "pumpkin_stem_connected" },
  { identifier: "purple_dye", png: "dye_powder_purple" },
  { identifier: "purple_glazed_terracotta", png: "glazed_terracotta_purple" },
  { identifier: "purpur_block", png: "purpur_block" },
  { identifier: "purpur_stairs", png: "purpur_block" },
  { identifier: "quartz", png: "quartz" },
  { identifier: "quartz_block", png: "quartz_block_top" },
  { identifier: "quartz_bricks", png: "quartz_bricks" },
  { identifier: "quartz_ore", png: "quartz_ore" },
  { identifier: "quartz_stairs", png: "quartz_block_top" },
  { identifier: "rabbit", png: "rabbit_raw" },
  { identifier: "rabbit_foot", png: "rabbit_foot" },
  { identifier: "rabbit_hide", png: "rabbit_hide" },
  { identifier: "rabbit_spawn_egg", png: "egg_rabbit" },
  { identifier: "rabbit_stew", png: "rabbit_stew" },
  { identifier: "rail", png: "rail_normal" },
  //{ identifier: "rapid_fertilizer", png: "rapid_fertilizer" },
  { identifier: "ravager_spawn_egg", png: "egg_ravager" },
  { identifier: "raw_copper", png: "raw_copper" },
  { identifier: "raw_copper_block", png: "raw_copper_block" },
  { identifier: "raw_gold", png: "raw_gold" },
  { identifier: "raw_gold_block", png: "raw_gold_block" },
  { identifier: "raw_iron", png: "raw_iron" },
  { identifier: "raw_iron_block", png: "raw_iron_block" },
  { identifier: "real_double_stone_slab", png: "stone" },
  { identifier: "real_double_stone_slab2", png: "stone" },
  { identifier: "real_double_stone_slab3", png: "stone" },
  { identifier: "real_double_stone_slab4", png: "stone" },
  { identifier: "red_dye", png: "dye_powder_red" },
  { identifier: "red_flower", png: "flower_rose" },
  { identifier: "red_glazed_terracotta", png: "glazed_terracotta_red" },
  { identifier: "red_mushroom", png: "mushroom_red" },
  { identifier: "red_mushroom_block", png: "mushroom_block_skin_red" },
  { identifier: "red_nether_brick", png: "red_nether_brick" },
  { identifier: "red_nether_brick_stairs", png: "red_nether_brick" },
  { identifier: "red_sandstone", png: "red_sandstone_top" },
  { identifier: "red_sandstone_stairs", png: "red_sandstone_top" },
  { identifier: "redstone", png: "redstone_dust" },
  { identifier: "redstone_block", png: "redstone_block" },
  { identifier: "redstone_lamp", png: "redstone_lamp_off" },
  { identifier: "redstone_ore", png: "redstone_ore" },
  { identifier: "redstone_torch", png: "redstone_torch_on" },
  { identifier: "redstone_wire", png: "redstone_dust_line" },
  { identifier: "repeater", png: "repeater" },
  {
    identifier: "repeating_command_block",
    png: "repeating_command_block_front_mipmap"
  },
  { identifier: "reserved6", png: "stone" },
  { identifier: "respawn_anchor", png: "respawn_anchor_side4" },
  { identifier: "rotten_flesh", png: "rotten_flesh" },
  { identifier: "saddle", png: "saddle" },
  { identifier: "salmon", png: "fish_salmon_raw" },
  { identifier: "salmon_bucket", png: "bucket_salmon" },
  { identifier: "salmon_spawn_egg", png: "egg_salmon" },
  { identifier: "sand", png: "sand" },
  { identifier: "sandstone", png: "sandstone_top" },
  { identifier: "sandstone_stairs", png: "sandstone_top" },
  { identifier: "sapling", png: "sapling_oak" },
  { identifier: "scaffolding", png: "bamboo" },
  //{ identifier: "sculk_sensor", png: "sculk_sensor" },
  { identifier: "scute", png: "turtle_shell_piece" },
  { identifier: "sea_pickle", png: "sea_pickle" },
  { identifier: "seagrass", png: "seagrass_carried" },
  { identifier: "sealantern", png: "sea_lantern" },
  { identifier: "shears", png: "shears" },
  { identifier: "sheep_spawn_egg", png: "egg_sheep" },
  { identifier: "shield", png: "planks_oak" },
  { identifier: "shroomlight", png: "shroomlight" },
  { identifier: "shulker_box", png: "shulker_top_undyed" },
  { identifier: "shulker_shell", png: "shulker_shell" },
  { identifier: "shulker_spawn_egg", png: "egg_shulker" },
  { identifier: "silver_glazed_terracotta", png: "glazed_terracotta_silver" },
  { identifier: "silverfish_spawn_egg", png: "egg_silverfish" },
  { identifier: "skeleton_horse_spawn_egg", png: "egg_skeletonhorse" },
  { identifier: "skeleton_spawn_egg", png: "egg_skeleton" },
  { identifier: "skull", png: "bone" },
  { identifier: "skull_banner_pattern", png: "banner_pattern" },
  { identifier: "slime", png: "slime" },
  { identifier: "slime_ball", png: "slimeball" },
  { identifier: "slime_spawn_egg", png: "egg_slime" },
  { identifier: "small_amethyst_bud", png: "small_amethyst_bud" },
  { identifier: "small_dripleaf_block", png: "big_dripleaf_top" },
  { identifier: "smithing_table", png: "smithing_table_side" },
  { identifier: "smoker", png: "smoker_front_off" },
  { identifier: "smooth_basalt", png: "smooth_basalt" },
  { identifier: "smooth_quartz_stairs", png: "quartz_block_top" },
  { identifier: "smooth_red_sandstone_stairs", png: "red_sandstone_top" },
  { identifier: "smooth_sandstone_stairs", png: "sandstone_top" },
  { identifier: "smooth_stone", png: "stone_slab_top" },
  { identifier: "snow", png: "snow" },
  { identifier: "snow_layer", png: "snow" },
  { identifier: "snowball", png: "snowball" },
  { identifier: "soul_campfire", png: "soul_campfire" },
  { identifier: "soul_fire", png: "fire_0_placeholder" },
  { identifier: "soul_lantern", png: "soul_lantern" },
  { identifier: "soul_sand", png: "soul_sand" },
  { identifier: "soul_soil", png: "soul_soil" },
  { identifier: "soul_torch", png: "soul_torch" },
  //{ identifier: "sparkler", png: "sparkler" },
  { identifier: "spawn_egg", png: "spawn_egg" },
  { identifier: "spider_eye", png: "spider_eye" },
  { identifier: "spider_spawn_egg", png: "egg_spider" },
  { identifier: "splash_potion", png: "potion_bottle_splash_waterBreathing" },
  { identifier: "sponge", png: "sponge" },
  { identifier: "spore_blossom", png: "spore_blossom" },
  { identifier: "spruce_boat", png: "boat_spruce" },
  { identifier: "spruce_button", png: "planks_spruce" },
  { identifier: "spruce_door", png: "door_spruce" },
  { identifier: "spruce_fence_gate", png: "planks_spruce" },
  { identifier: "spruce_pressure_plate", png: "planks_spruce" },
  { identifier: "spruce_sign", png: "sign_spruce" },
  { identifier: "spruce_stairs", png: "planks_spruce" },
  { identifier: "spruce_standing_sign", png: "sign_spruce" },
  { identifier: "spruce_trapdoor", png: "spruce_trapdoor" },
  { identifier: "spruce_wall_sign", png: "sign_spruce" },
  { identifier: "spyglass", png: "spyglass" },
  { identifier: "squid_spawn_egg", png: "egg_squid" },
  { identifier: "stained_glass", png: "glass" },
  { identifier: "stained_glass_pane", png: "glass" },
  { identifier: "stained_hardened_clay", png: "hardened_clay" },
  { identifier: "standing_banner", png: "wool_colored_white" },
  { identifier: "standing_sign", png: "sign" },
  { identifier: "stick", png: "stick" },
  { identifier: "sticky_piston", png: "piston_side" },
  { identifier: "stickypistonarmcollision", png: "piston_side" },
  { identifier: "stone", png: "stone" },
  { identifier: "stone_axe", png: "stone_axe" },
  { identifier: "stone_brick_stairs", png: "stonebrick" },
  { identifier: "stone_button", png: "stone" },
  { identifier: "stone_hoe", png: "stone_hoe" },
  { identifier: "stone_pickaxe", png: "stone_pickaxe" },
  { identifier: "stone_pressure_plate", png: "stone" },
  { identifier: "stone_shovel", png: "stone_shovel" },
  { identifier: "stone_stairs", png: "stone" },
  { identifier: "stone_sword", png: "stone_sword" },
  { identifier: "stonebrick", png: "stonebrick" },
  { identifier: "stonecutter", png: "stonecutter_side" },
  { identifier: "stonecutter_block", png: "stonecutter2_side" },
  { identifier: "stray_spawn_egg", png: "egg_stray" },
  { identifier: "strider_spawn_egg", png: "egg_lava_slime" },
  { identifier: "string", png: "string" },
  { identifier: "stripped_acacia_log", png: "stripped_acacia_log" },
  { identifier: "stripped_birch_log", png: "stripped_birch_log" },
  { identifier: "stripped_crimson_hyphae", png: "stripped_crimson_stem_side" },
  { identifier: "stripped_crimson_stem", png: "stripped_crimson_stem_side" },
  { identifier: "stripped_dark_oak_log", png: "stripped_dark_oak_log" },
  { identifier: "stripped_jungle_log", png: "stripped_jungle_log" },
  { identifier: "stripped_oak_log", png: "stripped_oak_log" },
  { identifier: "stripped_spruce_log", png: "stripped_spruce_log" },
  { identifier: "stripped_warped_hyphae", png: "stripped_warped_stem_side" },
  { identifier: "stripped_warped_stem", png: "stripped_warped_stem_side" },
  { identifier: "structure_block", png: "structure_block" },
  { identifier: "structure_void", png: "structure_void" },
  { identifier: "sugar", png: "sugar" },
  { identifier: "sugar_cane", png: "reeds" },
  { identifier: "suspicious_stew", png: "suspicious_stew" },
  { identifier: "sweet_berries", png: "sweet_berries" },
  { identifier: "sweet_berry_bush", png: "sweet_berry_bush_stage3" },
  { identifier: "tallgrass", png: "double_plant_grass_carried" },
  { identifier: "target", png: "target_top" },
  { identifier: "tinted_glass", png: "tinted_glass" },
  { identifier: "tnt", png: "tnt_side" },
  { identifier: "tnt_minecart", png: "minecart_tnt" },
  { identifier: "torch", png: "torch_on" },
  { identifier: "totem_of_undying", png: "totem" },
  { identifier: "trapdoor", png: "trapdoor" },
  { identifier: "trapped_chest", png: "trapped_chest_front" },
  { identifier: "trident", png: "trident" },
  { identifier: "tripwire", png: "trip_wire_source" },
  { identifier: "tripwire_hook", png: "trip_wire_source" },
  { identifier: "tropical_fish", png: "fish_clownfish_raw" },
  { identifier: "tropical_fish_bucket", png: "bucket_tropical" },
  { identifier: "tropical_fish_spawn_egg", png: "egg_fish" },
  { identifier: "tuff", png: "tuff" },
  { identifier: "turtle_egg", png: "turtle_egg" },
  { identifier: "turtle_helmet", png: "turtle_helmet" },
  { identifier: "turtle_spawn_egg", png: "egg_turtle" },
  { identifier: "twisting_vines", png: "twisting_vines_base" },
  //{ identifier: "underwater_torch", png: "underwater_torch" },
  { identifier: "undyed_shulker_box", png: "shulker_top_undyed" },
  //{ identifier: "unknown", png: "unknown" },
  { identifier: "unlit_redstone_torch", png: "redstone_torch_off" },
  { identifier: "unpowered_comparator", png: "comparator_off" },
  { identifier: "unpowered_repeater", png: "repeater_off" },
  { identifier: "vex_spawn_egg", png: "egg_vex" },
  { identifier: "villager_spawn_egg", png: "egg_villager" },
  { identifier: "vindicator_spawn_egg", png: "egg_vindicator" },
  { identifier: "vine", png: "vine" },
  { identifier: "wall_banner", png: "wool_colored_white" },
  { identifier: "wall_sign", png: "sign" },
  { identifier: "wandering_trader_spawn_egg", png: "egg_wanderingtrader" },
  { identifier: "warped_button", png: "warped_planks" },
  { identifier: "warped_door", png: "warped_door" },
  { identifier: "warped_double_slab", png: "warped_planks" },
  { identifier: "warped_fence", png: "warped_planks" },
  { identifier: "warped_fence_gate", png: "warped_planks" },
  { identifier: "warped_fungus", png: "warped_fungus" },
  { identifier: "warped_fungus_on_a_stick", png: "warped_fungus_on_a_stick" },
  { identifier: "warped_hyphae", png: "warped_stem_side" },
  { identifier: "warped_nylium", png: "warped_nylium_side" },
  { identifier: "warped_planks", png: "warped_planks" },
  { identifier: "warped_pressure_plate", png: "warped_planks" },
  { identifier: "warped_roots", png: "warped_roots" },
  { identifier: "warped_sign", png: "sign_warped" },
  { identifier: "warped_slab", png: "warped_planks" },
  { identifier: "warped_stairs", png: "warped_planks" },
  { identifier: "warped_standing_sign", png: "sign_warped" },
  { identifier: "warped_stem", png: "warped_stem_side" },
  { identifier: "warped_trapdoor", png: "warped_trapdoor" },
  { identifier: "warped_wall_sign", png: "sign_warped" },
  { identifier: "warped_wart_block", png: "warped_wart_block" },
  { identifier: "water", png: "water_placeholder" },
  { identifier: "water_bucket", png: "bucket_water" },
  { identifier: "waterlily", png: "waterlily" },
  { identifier: "waxed_copper", png: "copper_block" },
  { identifier: "waxed_cut_copper", png: "cut_copper" },
  { identifier: "waxed_cut_copper_slab", png: "cut_copper" },
  { identifier: "waxed_cut_copper_stairs", png: "cut_copper" },
  {
    identifier: "waxed_double_cut_copper_slab",
    png: "cut_copper"
  },
  { identifier: "waxed_exposed_copper", png: "exposed_copper" },
  { identifier: "waxed_exposed_cut_copper", png: "exposed_cut_copper" },
  {
    identifier: "waxed_exposed_cut_copper_slab",
    png: "exposed_cut_copper"
  },
  {
    identifier: "waxed_exposed_cut_copper_stairs",
    png: "exposed_cut_copper"
  },
  {
    identifier: "waxed_exposed_double_cut_copper_slab",
    png: "exposed_cut_copper"
  },
  { identifier: "waxed_oxidized_copper", png: "oxidized_copper" },
  { identifier: "waxed_oxidized_cut_copper", png: "oxidized_cut_copper" },
  {
    identifier: "waxed_oxidized_cut_copper_slab",
    png: "oxidized_cut_copper"
  },
  {
    identifier: "waxed_oxidized_cut_copper_stairs",
    png: "oxidized_cut_copper"
  },
  {
    identifier: "waxed_oxidized_double_cut_copper_slab",
    png: "oxidized_cut_copper"
  },
  { identifier: "waxed_weathered_copper", png: "weathered_copper" },
  {
    identifier: "waxed_weathered_cut_copper",
    png: "weathered_cut_copper"
  },
  {
    identifier: "waxed_weathered_cut_copper_slab",
    png: "weathered_cut_copper"
  },
  {
    identifier: "waxed_weathered_cut_copper_stairs",
    png: "weathered_cut_copper"
  },
  {
    identifier: "waxed_weathered_double_cut_copper_slab",
    png: "weathered_cut_copper"
  },
  { identifier: "weathered_copper", png: "weathered_copper" },
  { identifier: "weathered_cut_copper", png: "weathered_cut_copper" },
  { identifier: "weathered_cut_copper_slab", png: "weathered_cut_copper" },
  {
    identifier: "weathered_cut_copper_stairs",
    png: "weathered_cut_copper"
  },
  {
    identifier: "weathered_double_cut_copper_slab",
    png: "weathered_cut_copper"
  },
  { identifier: "web", png: "web" },
  { identifier: "weeping_vines", png: "weeping_vines_base" },
  { identifier: "wheat", png: "wheat" },
  { identifier: "wheat_seeds", png: "seeds_wheat" },
  { identifier: "white_dye", png: "dye_powder_white_new" },
  { identifier: "white_glazed_terracotta", png: "glazed_terracotta_white" },
  { identifier: "witch_spawn_egg", png: "egg_witch" },
  { identifier: "wither_rose", png: "flower_wither_rose" },
  { identifier: "wither_skeleton_spawn_egg", png: "egg_wither" },
  { identifier: "wolf_spawn_egg", png: "egg_wolf" },
  { identifier: "wood", png: "log_oak" },
  { identifier: "wooden_axe", png: "wood_axe" },
  { identifier: "wooden_button", png: "planks_oak" },
  { identifier: "wooden_door", png: "door_wood" },
  { identifier: "wooden_hoe", png: "wood_hoe" },
  { identifier: "wooden_pickaxe", png: "wood_pickaxe" },
  { identifier: "wooden_pressure_plate", png: "planks_oak" },
  { identifier: "wooden_shovel", png: "wood_shovel" },
  { identifier: "wooden_slab", png: "planks_oak" },
  { identifier: "wooden_sword", png: "wood_sword" },
  { identifier: "wool", png: "wool_colored_white" },
  { identifier: "writable_book", png: "book_writable" },
  { identifier: "written_book", png: "book_written" },
  { identifier: "yellow_dye", png: "dye_powder_yellow" },
  { identifier: "yellow_flower", png: "flower_dandelion" },
  { identifier: "yellow_glazed_terracotta", png: "glazed_terracotta_yellow" },
  { identifier: "zoglin_spawn_egg", png: "egg_pigzombie" },
  { identifier: "zombie_horse_spawn_egg", png: "egg_zombiehorse" },
  { identifier: "zombie_pigman_spawn_egg", png: "egg_pigzombie" },
  { identifier: "zombie_spawn_egg", png: "egg_zombie" },
  { identifier: "zombie_villager_spawn_egg", png: "egg_zombievillager" }
];
